2>build_SPIRV_errors.log cls 
cd WickedEngine\shaders 
mkdir spirv
cd .. 
..\shadercompilers\dxc bloomSeparatePS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/bloomSeparatePS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc captureImpostorPS_albedo.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/captureImpostorPS_albedo.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc captureImpostorPS_normal.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/captureImpostorPS_normal.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc captureImpostorPS_surface.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/captureImpostorPS_surface.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc circleGS.hlsl -T gs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_GS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/circleGS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc circlePS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/circlePS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc circleVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/circleVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc cloudGeneratorCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/cloudGeneratorCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc colorGradePS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/colorGradePS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc copytexture2D_float4CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/copytexture2D_float4CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc copytexture2D_float4_borderexpandCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/copytexture2D_float4_borderexpandCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc copytexture2D_unorm4CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/copytexture2D_unorm4CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc copytexture2D_unorm4_borderexpandCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/copytexture2D_unorm4_borderexpandCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc cubeMapPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/cubeMapPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc cubeShadowGS.hlsl -T gs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_GS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/cubeShadowGS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc cubeShadowGS_alphatest.hlsl -T gs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_GS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/cubeShadowGS_alphatest.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc cubeShadowPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/cubeShadowPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc cubeShadowPS_alphatest.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/cubeShadowPS_alphatest.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc cubeShadowVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/cubeShadowVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc cubeShadowVS_alphatest.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/cubeShadowVS_alphatest.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc cubeVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/cubeVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc decalPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/decalPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc decalVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/decalVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc deferredPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/deferredPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc depthofFieldPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/depthofFieldPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc dirLightPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/dirLightPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc dirLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/dirLightVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc discLightPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/discLightPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc downsampleDepthBuffer4xPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/downsampleDepthBuffer4xPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticlePS_soft_distortion.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticlePS_soft_distortion.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_emitCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_emitCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_emitCS_FROMMESH.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_emitCS_FROMMESH.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_finishUpdateCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_finishUpdateCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_sphpartitionoffsetsCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_sphpartitionoffsetsCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_sphpartitionoffsetsresetCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_sphpartitionoffsetsresetCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc filterEnvMapCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/filterEnvMapCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc generateMIPChain2D_float4_BicubicCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/generateMIPChain2D_float4_BicubicCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc generateMIPChain2D_unorm4_BicubicCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/generateMIPChain2D_unorm4_BicubicCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc generateMIPChain2D_unorm4_GaussianCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/generateMIPChain2D_unorm4_GaussianCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc generateMIPChain2D_unorm4_SimpleFilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/generateMIPChain2D_unorm4_SimpleFilterCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc generateMIPChain3D_unorm4_GaussianCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/generateMIPChain3D_unorm4_GaussianCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc generateMIPChain3D_unorm4_SimpleFilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/generateMIPChain3D_unorm4_SimpleFilterCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc generateMIPChainCubeArray_float4_SimpleFilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/generateMIPChainCubeArray_float4_SimpleFilterCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc generateMIPChainCubeArray_unorm4_SimpleFilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/generateMIPChainCubeArray_unorm4_SimpleFilterCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc generateMIPChainCube_float4_SimpleFilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/generateMIPChainCube_float4_SimpleFilterCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc generateMIPChainCube_unorm4_SimpleFilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/generateMIPChainCube_unorm4_SimpleFilterCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc gpusortlib_kickoffSortCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/gpusortlib_kickoffSortCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_kickoffUpdateCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_kickoffUpdateCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_sphdensityCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_sphdensityCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_sphforceCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_sphforceCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_simulateCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_simulateCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_simulateCS_DEPTHCOLLISIONS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_simulateCS_DEPTHCOLLISIONS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_simulateCS_SORTING.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_simulateCS_SORTING.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_simulateCS_SORTING_DEPTHCOLLISIONS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_simulateCS_SORTING_DEPTHCOLLISIONS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc gpusortlib_sortCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/gpusortlib_sortCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc gpusortlib_sortInnerCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/gpusortlib_sortInnerCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc gpusortlib_sortStepCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/gpusortlib_sortStepCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_sphpartitionCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_sphpartitionCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc environmentalLightPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/environmentalLightPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc envMapGS.hlsl -T gs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_GS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/envMapGS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc envMapPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/envMapPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc envMapVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/envMapVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc envMap_skyGS.hlsl -T gs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_GS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/envMap_skyGS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc envMap_skyPS_dynamic.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/envMap_skyPS_dynamic.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc envMap_skyPS_static.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/envMap_skyPS_static.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc envMap_skyVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/envMap_skyVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc fft_512x512_c2c_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/fft_512x512_c2c_CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc fft_512x512_c2c_v2_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/fft_512x512_c2c_v2_CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc fontPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/fontPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc fontVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/fontVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc forceFieldVisualizerPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/forceFieldVisualizerPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc forceFieldPlaneVisualizerVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/forceFieldPlaneVisualizerVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc forceFieldPointVisualizerVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/forceFieldPointVisualizerVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc fxaa.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/fxaa.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc generateMIPChain2D_float4_GaussianCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/generateMIPChain2D_float4_GaussianCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc generateMIPChain2D_float4_SimpleFilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/generateMIPChain2D_float4_SimpleFilterCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc generateMIPChain3D_float4_GaussianCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/generateMIPChain3D_float4_GaussianCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc generateMIPChain3D_float4_SimpleFilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/generateMIPChain3D_float4_SimpleFilterCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc hairparticlePS_simplest.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/hairparticlePS_simplest.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc hairparticle_simulateCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/hairparticle_simulateCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc imagePS_bicubic.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/imagePS_bicubic.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc imagePS_distortion_bicubic.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/imagePS_distortion_bicubic.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc imagePS_distortion_masked_bicubic.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/imagePS_distortion_masked_bicubic.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc imagePS_masked_bicubic.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/imagePS_masked_bicubic.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc imagePS_separatenormalmap_bicubic.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/imagePS_separatenormalmap_bicubic.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc impostorPS_alphatestonly.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/impostorPS_alphatestonly.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc impostorPS_deferred.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/impostorPS_deferred.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc impostorPS_forward.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/impostorPS_forward.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc impostorPS_simple.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/impostorPS_simple.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc impostorPS_tiledforward.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/impostorPS_tiledforward.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc impostorPS_wire.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/impostorPS_wire.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc impostorVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/impostorVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_deferred_normalmap_planarreflection.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_deferred_normalmap_planarreflection.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_deferred_planarreflection.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_deferred_planarreflection.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_hologram.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_hologram.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc oceanSurfacePS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/oceanSurfacePS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc oceanSurfaceVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/oceanSurfaceVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc hairparticleVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/hairparticleVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc blurPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/blurPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc imagePS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/imagePS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc imagePS_separatenormalmap.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/imagePS_separatenormalmap.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc imagePS_distortion.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/imagePS_distortion.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc imagePS_distortion_masked.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/imagePS_distortion_masked.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc imagePS_masked.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/imagePS_masked.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc imageVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/imageVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lensFlareGS.hlsl -T gs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_GS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lensFlareGS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lensFlarePS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lensFlarePS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lensFlareVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lensFlareVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lightCullingCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lightCullingCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lightCullingCS_ADVANCED.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lightCullingCS_ADVANCED.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lightCullingCS_ADVANCED_DEBUG.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lightCullingCS_ADVANCED_DEBUG.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lightCullingCS_DEBUG.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lightCullingCS_DEBUG.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lightCullingCS_DEFERRED.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lightCullingCS_DEFERRED.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lightCullingCS_DEFERRED_ADVANCED.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lightCullingCS_DEFERRED_ADVANCED.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lightCullingCS_DEFERRED_ADVANCED_DEBUG.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lightCullingCS_DEFERRED_ADVANCED_DEBUG.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lightCullingCS_DEFERRED_DEBUG.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lightCullingCS_DEFERRED_DEBUG.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lightShaftPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lightShaftPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc linDepthPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/linDepthPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc linesPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/linesPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc linesVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/linesVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc luminancePass1CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/luminancePass1CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc luminancePass2CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/luminancePass2CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc motionBlurPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/motionBlurPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectDS.hlsl -T ds_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_DS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectDS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectGS_voxelizer.hlsl -T gs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_GS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectGS_voxelizer.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectHS.hlsl -T hs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_HS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectHS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_alphatestonly.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_alphatestonly.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_debug.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_debug.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_deferred.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_deferred.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_blackout.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_blackout.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_deferred_normalmap.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_deferred_normalmap.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_deferred_normalmap_pom.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_deferred_normalmap_pom.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_deferred_pom.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_deferred_pom.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward_normalmap.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward_normalmap.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward_normalmap_planarreflection.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward_normalmap_planarreflection.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward_normalmap_pom.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward_normalmap_pom.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward_planarreflection.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward_planarreflection.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward_pom.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward_pom.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward_transparent.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward_transparent.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward_transparent_normalmap_planarreflection.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward_transparent_normalmap_planarreflection.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward_transparent_normalmap_pom.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward_transparent_normalmap_pom.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward_transparent_planarreflection.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward_transparent_planarreflection.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward_transparent_pom.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward_transparent_pom.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_simplest.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_simplest.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_textureonly.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_textureonly.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward_transparent_normalmap.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward_transparent_normalmap.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_normalmap.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward_normalmap.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_normalmap_planarreflection.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward_normalmap_planarreflection.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_normalmap_pom.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward_normalmap_pom.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_planarreflection.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward_planarreflection.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_pom.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward_pom.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_transparent.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward_transparent.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_transparent_normalmap.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward_transparent_normalmap.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_transparent_normalmap_planarreflection.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward_transparent_normalmap_planarreflection.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_transparent_normalmap_pom.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward_transparent_normalmap_pom.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_transparent_planarreflection.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward_transparent_planarreflection.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_transparent_pom.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward_transparent_pom.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_water.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward_water.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_voxelizer.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_voxelizer.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectVS_common_tessellation.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectVS_common_tessellation.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectVS_common.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectVS_common.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectVS_debug.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectVS_debug.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectVS_positionstream.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectVS_positionstream.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectVS_simple.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectVS_simple.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectVS_simple_tessellation.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectVS_simple_tessellation.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectVS_voxelizer.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectVS_voxelizer.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc oceanSimulatorCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/oceanSimulatorCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc oceanSurfaceSimplePS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/oceanSurfaceSimplePS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc oceanUpdateDisplacementMapCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/oceanUpdateDisplacementMapCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc oceanUpdateGradientFoldingCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/oceanUpdateGradientFoldingCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc outlinePS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/outlinePS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc pointLightPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/pointLightPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc pointLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/pointLightVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticlePS_soft.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticlePS_soft.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticlePS_simplest.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticlePS_simplest.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticleVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticleVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc hairparticlePS_alphatestonly.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/hairparticlePS_alphatestonly.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc hairparticlePS_deferred.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/hairparticlePS_deferred.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc hairparticlePS_forward.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/hairparticlePS_forward.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc hairparticlePS_tiledforward.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/hairparticlePS_tiledforward.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc bvh_propagateaabbCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/bvh_propagateaabbCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc bvh_hierarchyCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/bvh_hierarchyCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc raytrace_clearCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/raytrace_clearCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc bvh_primitivesCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/bvh_primitivesCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc raytrace_debugbvhPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/raytrace_debugbvhPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc raytrace_lightsamplingCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/raytrace_lightsamplingCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc raytrace_kickjobsCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/raytrace_kickjobsCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc raytrace_screenVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/raytrace_screenVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc rectangleLightPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/rectangleLightPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc renderlightmapPS_indirect.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/renderlightmapPS_indirect.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc renderlightmapPS_direct.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/renderlightmapPS_direct.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc renderlightmapVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/renderlightmapVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc reprojectDepthBufferPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/reprojectDepthBufferPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc resolveMSAADepthStencilCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/resolveMSAADepthStencilCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc screenPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/screenPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc screenPS_bicubic.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/screenPS_bicubic.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc screenVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/screenVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc shadowPS_alphatest.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/shadowPS_alphatest.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc shadowPS_transparent.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/shadowPS_transparent.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc shadowPS_water.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/shadowPS_water.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc shadowVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/shadowVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc shadowVS_alphatest.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/shadowVS_alphatest.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc shadowVS_transparent.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/shadowVS_transparent.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc sharpenPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/sharpenPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc skinningCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/skinningCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc skinningCS_LDS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/skinningCS_LDS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc skyPS_static.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/skyPS_static.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc skyPS_dynamic.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/skyPS_dynamic.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc skyVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/skyVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc sphereLightPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/sphereLightPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc sphereVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/sphereVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc spotLightPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/spotLightPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc spotLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/spotLightVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc ssao.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/ssao.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc ssr.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/ssr.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc ssss.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/ssss.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc sunPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/sunPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc temporalAAResolvePS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/temporalAAResolvePS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc tileFrustumsCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/tileFrustumsCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc toneMapPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/toneMapPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc raytrace_launchCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/raytrace_launchCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc raytrace_primaryCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/raytrace_primaryCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc trailPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/trailPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc trailVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/trailVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc tubeLightPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/tubeLightPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc vDiscLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/vDiscLightVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lightVisualizerPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lightVisualizerPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc volumetricLight_DirectionalPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/volumetricLight_DirectionalPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc volumetricLight_PointPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/volumetricLight_PointPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc volumetricLight_SpotPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/volumetricLight_SpotPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc voxelClearOnlyNormalCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/voxelClearOnlyNormalCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc voxelGS.hlsl -T gs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_GS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/voxelGS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc voxelPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/voxelPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc voxelRadianceSecondaryBounceCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/voxelRadianceSecondaryBounceCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc voxelSceneCopyClearCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/voxelSceneCopyClearCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc voxelSceneCopyClear_TemporalSmoothing.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/voxelSceneCopyClear_TemporalSmoothing.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc voxelVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/voxelVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc vPointLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/vPointLightVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc vRectangleLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/vRectangleLightVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc vSphereLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/vSphereLightVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc vSpotLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/vSpotLightVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward_water.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward_water.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc vTubeLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/vTubeLightVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc waterVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/waterVS.cso  2>>../build_SPIRV_errors.log 
cd .. 
