2>build_HLSL6_errors.log cls 
cd WickedEngine\shaders 
mkdir hlsl6
cd .. 
..\shadercompilers\dxc bloomSeparatePS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/bloomSeparatePS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc captureImpostorPS_albedo.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/captureImpostorPS_albedo.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc captureImpostorPS_normal.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/captureImpostorPS_normal.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc captureImpostorPS_surface.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/captureImpostorPS_surface.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc circleGS.hlsl -T gs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/circleGS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc circlePS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/circlePS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc circleVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/circleVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc cloudGeneratorCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/cloudGeneratorCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc colorGradePS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/colorGradePS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc copytexture2D_float4CS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/copytexture2D_float4CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc copytexture2D_float4_borderexpandCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/copytexture2D_float4_borderexpandCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc copytexture2D_unorm4CS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/copytexture2D_unorm4CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc copytexture2D_unorm4_borderexpandCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/copytexture2D_unorm4_borderexpandCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc cubeMapPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/cubeMapPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc cubeShadowGS.hlsl -T gs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/cubeShadowGS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc cubeShadowGS_alphatest.hlsl -T gs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/cubeShadowGS_alphatest.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc cubeShadowPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/cubeShadowPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc cubeShadowPS_alphatest.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/cubeShadowPS_alphatest.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc cubeShadowVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/cubeShadowVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc cubeShadowVS_alphatest.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/cubeShadowVS_alphatest.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc cubeVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/cubeVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc decalPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/decalPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc decalVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/decalVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc deferredPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/deferredPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc depthofFieldPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/depthofFieldPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc dirLightPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/dirLightPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc dirLightVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/dirLightVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc discLightPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/discLightPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc downsampleDepthBuffer4xPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/downsampleDepthBuffer4xPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticlePS_soft_distortion.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticlePS_soft_distortion.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_emitCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_emitCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_emitCS_FROMMESH.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_emitCS_FROMMESH.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_finishUpdateCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_finishUpdateCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_sphpartitionoffsetsCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_sphpartitionoffsetsCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_sphpartitionoffsetsresetCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_sphpartitionoffsetsresetCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc filterEnvMapCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/filterEnvMapCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc generateMIPChain2D_float4_BicubicCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/generateMIPChain2D_float4_BicubicCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc generateMIPChain2D_unorm4_BicubicCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/generateMIPChain2D_unorm4_BicubicCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc generateMIPChain2D_unorm4_GaussianCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/generateMIPChain2D_unorm4_GaussianCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc generateMIPChain2D_unorm4_SimpleFilterCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/generateMIPChain2D_unorm4_SimpleFilterCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc generateMIPChain3D_unorm4_GaussianCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/generateMIPChain3D_unorm4_GaussianCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc generateMIPChain3D_unorm4_SimpleFilterCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/generateMIPChain3D_unorm4_SimpleFilterCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc generateMIPChainCubeArray_float4_SimpleFilterCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/generateMIPChainCubeArray_float4_SimpleFilterCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc generateMIPChainCubeArray_unorm4_SimpleFilterCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/generateMIPChainCubeArray_unorm4_SimpleFilterCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc generateMIPChainCube_float4_SimpleFilterCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/generateMIPChainCube_float4_SimpleFilterCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc generateMIPChainCube_unorm4_SimpleFilterCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/generateMIPChainCube_unorm4_SimpleFilterCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc gpusortlib_kickoffSortCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/gpusortlib_kickoffSortCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_kickoffUpdateCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_kickoffUpdateCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_sphdensityCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_sphdensityCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_sphforceCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_sphforceCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_simulateCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_simulateCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_simulateCS_DEPTHCOLLISIONS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_simulateCS_DEPTHCOLLISIONS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_simulateCS_SORTING.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_simulateCS_SORTING.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_simulateCS_SORTING_DEPTHCOLLISIONS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_simulateCS_SORTING_DEPTHCOLLISIONS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc gpusortlib_sortCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/gpusortlib_sortCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc gpusortlib_sortInnerCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/gpusortlib_sortInnerCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc gpusortlib_sortStepCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/gpusortlib_sortStepCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_sphpartitionCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_sphpartitionCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc environmentalLightPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/environmentalLightPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc envMapGS.hlsl -T gs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/envMapGS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc envMapPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/envMapPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc envMapVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/envMapVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc envMap_skyGS.hlsl -T gs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/envMap_skyGS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc envMap_skyPS_dynamic.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/envMap_skyPS_dynamic.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc envMap_skyPS_static.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/envMap_skyPS_static.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc envMap_skyVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/envMap_skyVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc fft_512x512_c2c_CS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/fft_512x512_c2c_CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc fft_512x512_c2c_v2_CS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/fft_512x512_c2c_v2_CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc fontPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/fontPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc fontVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/fontVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc forceFieldVisualizerPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/forceFieldVisualizerPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc forceFieldPlaneVisualizerVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/forceFieldPlaneVisualizerVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc forceFieldPointVisualizerVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/forceFieldPointVisualizerVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc fxaa.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/fxaa.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc generateMIPChain2D_float4_GaussianCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/generateMIPChain2D_float4_GaussianCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc generateMIPChain2D_float4_SimpleFilterCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/generateMIPChain2D_float4_SimpleFilterCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc generateMIPChain3D_float4_GaussianCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/generateMIPChain3D_float4_GaussianCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc generateMIPChain3D_float4_SimpleFilterCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/generateMIPChain3D_float4_SimpleFilterCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc hairparticlePS_simplest.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/hairparticlePS_simplest.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc hairparticle_simulateCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/hairparticle_simulateCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc imagePS_bicubic.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/imagePS_bicubic.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc imagePS_distortion_bicubic.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/imagePS_distortion_bicubic.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc imagePS_distortion_masked_bicubic.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/imagePS_distortion_masked_bicubic.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc imagePS_masked_bicubic.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/imagePS_masked_bicubic.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc imagePS_separatenormalmap_bicubic.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/imagePS_separatenormalmap_bicubic.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc impostorPS_alphatestonly.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/impostorPS_alphatestonly.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc impostorPS_deferred.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/impostorPS_deferred.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc impostorPS_forward.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/impostorPS_forward.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc impostorPS_simple.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/impostorPS_simple.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc impostorPS_tiledforward.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/impostorPS_tiledforward.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc impostorVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/impostorVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_deferred_normalmap_planarreflection.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_deferred_normalmap_planarreflection.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_deferred_planarreflection.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_deferred_planarreflection.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_hologram.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_hologram.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc oceanSurfacePS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/oceanSurfacePS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc oceanSurfaceVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/oceanSurfaceVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc hairparticleVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/hairparticleVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc blurPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/blurPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc imagePS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/imagePS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc imagePS_separatenormalmap.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/imagePS_separatenormalmap.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc imagePS_distortion.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/imagePS_distortion.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc imagePS_distortion_masked.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/imagePS_distortion_masked.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc imagePS_masked.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/imagePS_masked.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc imageVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/imageVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lensFlareGS.hlsl -T gs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lensFlareGS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lensFlarePS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lensFlarePS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lensFlareVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lensFlareVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lightCullingCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lightCullingCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lightCullingCS_ADVANCED.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lightCullingCS_ADVANCED.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lightCullingCS_ADVANCED_DEBUG.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lightCullingCS_ADVANCED_DEBUG.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lightCullingCS_DEBUG.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lightCullingCS_DEBUG.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lightCullingCS_DEFERRED.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lightCullingCS_DEFERRED.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lightCullingCS_DEFERRED_ADVANCED.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lightCullingCS_DEFERRED_ADVANCED.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lightCullingCS_DEFERRED_ADVANCED_DEBUG.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lightCullingCS_DEFERRED_ADVANCED_DEBUG.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lightCullingCS_DEFERRED_DEBUG.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lightCullingCS_DEFERRED_DEBUG.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lightShaftPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lightShaftPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc linDepthPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/linDepthPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc linesPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/linesPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc linesVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/linesVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc luminancePass1CS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/luminancePass1CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc luminancePass2CS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/luminancePass2CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc motionBlurPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/motionBlurPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectDS.hlsl -T ds_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectDS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectGS_voxelizer.hlsl -T gs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectGS_voxelizer.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectHS.hlsl -T hs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectHS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_alphatestonly.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_alphatestonly.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_debug.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_debug.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_deferred.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_deferred.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_blackout.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_blackout.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_deferred_normalmap.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_deferred_normalmap.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_deferred_normalmap_pom.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_deferred_normalmap_pom.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_deferred_pom.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_deferred_pom.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward_normalmap.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward_normalmap.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward_normalmap_planarreflection.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward_normalmap_planarreflection.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward_normalmap_pom.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward_normalmap_pom.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward_planarreflection.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward_planarreflection.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward_pom.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward_pom.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward_transparent.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward_transparent.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward_transparent_normalmap_planarreflection.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward_transparent_normalmap_planarreflection.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward_transparent_normalmap_pom.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward_transparent_normalmap_pom.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward_transparent_planarreflection.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward_transparent_planarreflection.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward_transparent_pom.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward_transparent_pom.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_simplest.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_simplest.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_textureonly.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_textureonly.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward_transparent_normalmap.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward_transparent_normalmap.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_normalmap.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward_normalmap.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_normalmap_planarreflection.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward_normalmap_planarreflection.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_normalmap_pom.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward_normalmap_pom.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_planarreflection.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward_planarreflection.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_pom.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward_pom.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_transparent.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward_transparent.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_transparent_normalmap.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward_transparent_normalmap.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_transparent_normalmap_planarreflection.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward_transparent_normalmap_planarreflection.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_transparent_normalmap_pom.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward_transparent_normalmap_pom.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_transparent_planarreflection.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward_transparent_planarreflection.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_transparent_pom.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward_transparent_pom.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_water.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward_water.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_voxelizer.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_voxelizer.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectVS_common_tessellation.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectVS_common_tessellation.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectVS_common.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectVS_common.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectVS_debug.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectVS_debug.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectVS_positionstream.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectVS_positionstream.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectVS_simple.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectVS_simple.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectVS_simple_tessellation.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectVS_simple_tessellation.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectVS_voxelizer.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectVS_voxelizer.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc oceanSimulatorCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/oceanSimulatorCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc oceanSurfaceSimplePS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/oceanSurfaceSimplePS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc oceanUpdateDisplacementMapCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/oceanUpdateDisplacementMapCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc oceanUpdateGradientFoldingCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/oceanUpdateGradientFoldingCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc outlinePS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/outlinePS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc pointLightPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/pointLightPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc pointLightVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/pointLightVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticlePS_soft.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticlePS_soft.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticlePS_simplest.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticlePS_simplest.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticleVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticleVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc hairparticlePS_alphatestonly.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/hairparticlePS_alphatestonly.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc hairparticlePS_deferred.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/hairparticlePS_deferred.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc hairparticlePS_forward.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/hairparticlePS_forward.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc hairparticlePS_tiledforward.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/hairparticlePS_tiledforward.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc bvh_clusterprocessorCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/bvh_clusterprocessorCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc bvh_propagateaabbCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/bvh_propagateaabbCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc bvh_hierarchyCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/bvh_hierarchyCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc bvh_kickjobsCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/bvh_kickjobsCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc bvh_resetCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/bvh_resetCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc raytrace_clearCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/raytrace_clearCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc bvh_classificationCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/bvh_classificationCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc raytrace_lightsamplingCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/raytrace_lightsamplingCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc raytrace_kickjobsCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/raytrace_kickjobsCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc rectangleLightPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/rectangleLightPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc renderlightmapPS_indirect.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/renderlightmapPS_indirect.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc renderlightmapPS_direct.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/renderlightmapPS_direct.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc renderlightmapVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/renderlightmapVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc reprojectDepthBufferPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/reprojectDepthBufferPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc resolveMSAADepthStencilCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/resolveMSAADepthStencilCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc screenPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/screenPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc screenPS_bicubic.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/screenPS_bicubic.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc screenVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/screenVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc shadowPS_alphatest.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/shadowPS_alphatest.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc shadowPS_transparent.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/shadowPS_transparent.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc shadowPS_water.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/shadowPS_water.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc shadowVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/shadowVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc shadowVS_alphatest.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/shadowVS_alphatest.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc shadowVS_transparent.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/shadowVS_transparent.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc sharpenPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/sharpenPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc skinningCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/skinningCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc skinningCS_LDS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/skinningCS_LDS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc skyPS_static.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/skyPS_static.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc skyPS_dynamic.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/skyPS_dynamic.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc skyVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/skyVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc sphereLightPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/sphereLightPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc sphereVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/sphereVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc spotLightPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/spotLightPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc spotLightVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/spotLightVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc ssao.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/ssao.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc ssr.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/ssr.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc ssss.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/ssss.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc stereogramPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/stereogramPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc sunPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/sunPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc temporalAAResolvePS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/temporalAAResolvePS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc tileFrustumsCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/tileFrustumsCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc toneMapPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/toneMapPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc raytrace_launchCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/raytrace_launchCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc raytrace_primaryCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/raytrace_primaryCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc trailPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/trailPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc trailVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/trailVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc tubeLightPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/tubeLightPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc vDiscLightVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/vDiscLightVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lightVisualizerPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lightVisualizerPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc volumetricLight_DirectionalPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/volumetricLight_DirectionalPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc volumetricLight_PointPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/volumetricLight_PointPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc volumetricLight_SpotPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/volumetricLight_SpotPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc voxelClearOnlyNormalCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/voxelClearOnlyNormalCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc voxelGS.hlsl -T gs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/voxelGS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc voxelPS.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/voxelPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc voxelRadianceSecondaryBounceCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/voxelRadianceSecondaryBounceCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc voxelSceneCopyClearCS.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/voxelSceneCopyClearCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc voxelSceneCopyClear_TemporalSmoothing.hlsl -T cs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/voxelSceneCopyClear_TemporalSmoothing.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc voxelVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/voxelVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc vPointLightVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/vPointLightVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc vRectangleLightVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/vRectangleLightVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc vSphereLightVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/vSphereLightVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc vSpotLightVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/vSpotLightVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward_water.hlsl -T ps_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward_water.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc vTubeLightVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/vTubeLightVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc waterVS.hlsl -T vs_6_0  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/waterVS.cso  2>>../build_HLSL6_errors.log 
cd .. 
