#define OBJECTSHADER_COMPILE_PS
#define OBJECTSHADER_LAYOUT_COMMON
#define RAYTRACED_SHADOWS_ENABLED
#define OUTPUT_GBUFFER
#define TILEDFORWARD
#define DISABLE_ALPHATEST
#define BRDF_ANISOTROPIC
#include "objectHF.hlsli"

