#ifndef WI_RESOURCE_MAPPING_H
#define WI_RESOURCE_MAPPING_H

// Slot matchings:
////////////////////////////////////////////////////


// t slot:

// These are reserved slots for systems:
#define TEXSLOT_DEPTH				0
#define TEXSLOT_LINEARDEPTH			1

#define TEXSLOT_GBUFFER0			2
#define TEXSLOT_GBUFFER1			3
#define TEXSLOT_GBUFFER2			4

#define TEXSLOT_GLOBALENVMAP		6
#define TEXSLOT_GLOBALLIGHTMAP		7
#define TEXSLOT_ENVMAPARRAY			8
#define TEXSLOT_DECALATLAS			9

#define TEXSLOT_SHADOWARRAY_2D		10
#define TEXSLOT_SHADOWARRAY_CUBE	11
#define TEXSLOT_SHADOWARRAY_TRANSPARENT 12

#define TEXSLOT_VOXELRADIANCE		13

#define SBSLOT_TILEFRUSTUMS			14
#define SBSLOT_ENTITYTILES			15
#define SBSLOT_ENTITYARRAY			16
#define SBSLOT_MATRIXARRAY			17

#define TEXSLOT_FONTATLAS			19

// Ondemand textures are 2d textures and declared in shader globals, these can be used independently in any shader:
#define TEXSLOT_ONDEMAND0			20
#define TEXSLOT_ONDEMAND1			21
#define TEXSLOT_ONDEMAND2			22
#define TEXSLOT_ONDEMAND3			23
#define TEXSLOT_ONDEMAND4			24
#define TEXSLOT_ONDEMAND5			25
#define TEXSLOT_ONDEMAND6			26
#define TEXSLOT_ONDEMAND7			27
#define TEXSLOT_ONDEMAND8			28
#define TEXSLOT_ONDEMAND9			29
#define TEXSLOT_ONDEMAND_COUNT	(TEXSLOT_ONDEMAND9 - TEXSLOT_ONDEMAND0 + 1)

// These are reserved for demand of any type of textures in specific shaders:
#define TEXSLOT_UNIQUE0				30
#define TEXSLOT_UNIQUE1				31

#define TEXSLOT_COUNT		TEXSLOT_UNIQUE1

// Skinning:
#define SKINNINGSLOT_IN_VERTEX_POS	0
#define SKINNINGSLOT_IN_VERTEX_BON	1
#define SKINNINGSLOT_IN_BONEBUFFER	2


// wiRenderer object shader resources:
#define TEXSLOT_RENDERER_BASECOLORMAP		TEXSLOT_ONDEMAND0
#define TEXSLOT_RENDERER_NORMALMAP			TEXSLOT_ONDEMAND1
#define TEXSLOT_RENDERER_SURFACEMAP			TEXSLOT_ONDEMAND2
#define TEXSLOT_RENDERER_DISPLACEMENTMAP	TEXSLOT_ONDEMAND3
#define TEXSLOT_RENDERER_EMISSIVEMAP		TEXSLOT_ONDEMAND4
#define TEXSLOT_RENDERER_OCCLUSIONMAP		TEXSLOT_ONDEMAND5

// RenderPath texture mappings:
#define TEXSLOT_RENDERPATH_REFLECTION		TEXSLOT_ONDEMAND6
#define TEXSLOT_RENDERPATH_REFRACTION		TEXSLOT_ONDEMAND7
#define TEXSLOT_RENDERPATH_WATERRIPPLES		TEXSLOT_ONDEMAND8
#define TEXSLOT_RENDERPATH_SSAO				TEXSLOT_ONDEMAND8
#define TEXSLOT_RENDERPATH_SSR				TEXSLOT_ONDEMAND9


#endif // WI_RESOURCE_MAPPING_H
