#ifndef _SHADERINTEROP_TRACEDRENDERING_H_
#define _SHADERINTEROP_TRACEDRENDERING_H_
#include "ShaderInterop.h"

#define TRACEDRENDERING_PRIMARY_BLOCKSIZE 8

#endif // _SHADERINTEROP_TRACEDRENDERING_H_
