#ifndef WI_SHADERINTEROP_VULKAN_H
#define WI_SHADERINTEROP_VULKAN_H

#include "wiGraphicsDevice_SharedInternals.h"

#define VULKAN_BINDING_SHIFT_S 0
#define VULKAN_BINDING_SHIFT_B 16
#define VULKAN_BINDING_SHIFT_U 32
#define VULKAN_BINDING_SHIFT_T 40
#define VULKAN_BINDING_SHIFT_STAGE(stage) ((stage) * 100)

#endif // WI_SHADERINTEROP_VULKAN_H

