#ifndef _GRAPHICSDEVICE_SHAREDINTERNALS_H_
#define _GRAPHICSDEVICE_SHAREDINTERNALS_H_

// Descriptor layout counts:
#define GPU_RESOURCE_HEAP_CBV_COUNT		12
#define GPU_RESOURCE_HEAP_SRV_COUNT		64
#define GPU_RESOURCE_HEAP_UAV_COUNT		8
#define GPU_SAMPLER_HEAP_COUNT			16

#endif // _GRAPHICSDEVICE_SHAREDINTERNALS_H_
