#ifndef WI_GRAPHICSDEVICE_SHAREDINTERNALS_H
#define WI_GRAPHICSDEVICE_SHAREDINTERNALS_H

// Descriptor binding counts:
//	Feel free to increase these limits if not ebough
#define DESCRIPTORBINDER_CBV_COUNT		15
#define DESCRIPTORBINDER_SRV_COUNT		64
#define DESCRIPTORBINDER_UAV_COUNT		16
#define DESCRIPTORBINDER_SAMPLER_COUNT	16

#endif // WI_GRAPHICSDEVICE_SHAREDINTERNALS_H
