#pragma once

enum GRAPHICSTHREAD
{
	GRAPHICSTHREAD_REFLECTIONS,
	GRAPHICSTHREAD_SHADOWS,
	GRAPHICSTHREAD_SCENE,
	GRAPHICSTHREAD_MISC1,
	GRAPHICSTHREAD_MISC2,
	GRAPHICSTHREAD_MISC3,
	GRAPHICSTHREAD_COUNT
};