#define OBJECTSHADER_COMPILE_PS
#define OBJECTSHADER_LAYOUT_COMMON
#define DISABLE_DECALS
#define DISABLE_ENVMAPS
#define DISABLE_ALPHATEST
#define TILEDFORWARD
#define TRANSPARENT
#define WATER
#include "objectHF.hlsli"

