#ifndef WI_RESOURCE_MAPPING_H
#define WI_RESOURCE_MAPPING_H

// Slot matchings:
////////////////////////////////////////////////////


// t slot:

// These are reserved slots for systems:
#define TEXSLOT_DEPTH				0
#define TEXSLOT_LINEARDEPTH			1

#define TEXSLOT_GBUFFER0			2
#define TEXSLOT_GBUFFER1			3

#define TEXSLOT_ACCELERATION_STRUCTURE	4
#define TEXSLOT_BVH_COUNTER				4
#define TEXSLOT_BVH_PRIMITIVES			5
#define TEXSLOT_BVH_NODES				6




// Ondemand textures are 2d textures and declared in shader globals, these can be used independently in any shader:
#define TEXSLOT_ONDEMAND0			30
#define TEXSLOT_ONDEMAND1			31
#define TEXSLOT_ONDEMAND2			32
#define TEXSLOT_ONDEMAND3			33
#define TEXSLOT_ONDEMAND4			34
#define TEXSLOT_ONDEMAND5			35
#define TEXSLOT_ONDEMAND6			36
#define TEXSLOT_ONDEMAND7			37
#define TEXSLOT_ONDEMAND8			38
#define TEXSLOT_ONDEMAND9			39
#define TEXSLOT_ONDEMAND10			40
#define TEXSLOT_ONDEMAND11			41
#define TEXSLOT_ONDEMAND12			42
#define TEXSLOT_ONDEMAND13			43
#define TEXSLOT_ONDEMAND14			44
#define TEXSLOT_ONDEMAND15			45
#define TEXSLOT_ONDEMAND16			46
#define TEXSLOT_ONDEMAND17			47
#define TEXSLOT_ONDEMAND18			48
#define TEXSLOT_ONDEMAND19			49
#define TEXSLOT_ONDEMAND20			50
#define TEXSLOT_ONDEMAND21			51
#define TEXSLOT_ONDEMAND22			52
#define TEXSLOT_ONDEMAND23			53
#define TEXSLOT_ONDEMAND24			54
#define TEXSLOT_ONDEMAND25			55
#define TEXSLOT_ONDEMAND26			56
#define TEXSLOT_ONDEMAND27			57
#define TEXSLOT_ONDEMAND28			58
#define TEXSLOT_ONDEMAND29			59
#define TEXSLOT_ONDEMAND30			60
#define TEXSLOT_ONDEMAND31			61
#define TEXSLOT_ONDEMAND32			62
#define TEXSLOT_ONDEMAND33			63
#define TEXSLOT_ONDEMAND_COUNT	(TEXSLOT_ONDEMAND30 - TEXSLOT_ONDEMAND0 + 1)

#define TEXSLOT_COUNT				64


#endif // WI_RESOURCE_MAPPING_H
