//-------------------------------------------------------------------------------------------------------------------------------------------------------------
//
// Copyright 2023-2025 Apple Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//-------------------------------------------------------------------------------------------------------------------------------------------------------------

#ifndef IRFORMAT_H
#define IRFORMAT_H

typedef enum IRFormat
{
    IRFormatUnknown                            = 0,
    IRFormatR32G32B32A32Typeless               = 1,
    IRFormatR32G32B32A32Float                  = 2,
    IRFormatR32G32B32A32Uint                   = 3,
    IRFormatR32G32B32A32Sint                   = 4,
    IRFormatR32G32B32Typeless                  = 5,
    IRFormatR32G32B32Float                     = 6,
    IRFormatR32G32B32Uint                      = 7,
    IRFormatR32G32B32Sint                      = 8,
    IRFormatR16G16B16A16Typeless               = 9,
    IRFormatR16G16B16A16Float                  = 10,
    IRFormatR16G16B16A16Unorm                  = 11,
    IRFormatR16G16B16A16Uint                   = 12,
    IRFormatR16G16B16A16Snorm                  = 13,
    IRFormatR16G16B16A16Sint                   = 14,
    IRFormatR32G32Typeless                     = 15,
    IRFormatR32G32Float                        = 16,
    IRFormatR32G32Uint                         = 17,
    IRFormatR32G32Sint                         = 18,
    IRFormatR32G8X24Typeless                   = 19,
    IRFormatD32FloatS8X24Uint                  = 20,
    IRFormatR32FloatX8X24Typeless              = 21,
    IRFormatX32TypelessG8X24Uint               = 22,
    IRFormatR10G10B10A2Typeless                = 23,
    IRFormatR10G10B10A2Unorm                   = 24,
    IRFormatR10G10B10A2Uint                    = 25,
    IRFormatR11G11B10Float                     = 26,
    IRFormatR8G8B8A8Typeless                   = 27,
    IRFormatR8G8B8A8Unorm                      = 28,
    IRFormatR8G8B8A8Unorm_sRGB                 = 29,
    IRFormatR8G8B8A8Uint                       = 30,
    IRFormatR8G8B8A8Snorm                      = 31,
    IRFormatR8G8B8A8Sint                       = 32,
    IRFormatR16G16Typeless                     = 33,
    IRFormatR16G16Float                        = 34,
    IRFormatR16G16Unorm                        = 35,
    IRFormatR16G16Uint                         = 36,
    IRFormatR16G16Snorm                        = 37,
    IRFormatR16G16Sint                         = 38,
    IRFormatR32Typeless                        = 39,
    IRFormatD32Float                           = 40,
    IRFormatR32Float                           = 41,
    IRFormatR32Uint                            = 42,
    IRFormatR32Sint                            = 43,
    IRFormatR24G8Typeless                      = 44,
    IRFormatD24UnormS8Uint                     = 45,
    IRFormatR24UnormX8Typeless                 = 46,
    IRFormatX24TypelessG8Uint                  = 47,
    IRFormatR8G8Typeless                       = 48,
    IRFormatR8G8Unorm                          = 49,
    IRFormatR8G8Uint                           = 50,
    IRFormatR8G8Snorm                          = 51,
    IRFormatR8G8Sint                           = 52,
    IRFormatR16Typeless                        = 53,
    IRFormatR16Float                           = 54,
    IRFormatD16Unorm                           = 55,
    IRFormatR16Unorm                           = 56,
    IRFormatR16Uint                            = 57,
    IRFormatR16Snorm                           = 58,
    IRFormatR16Sint                            = 59,
    IRFormatR8Typeless                         = 60,
    IRFormatR8Unorm                            = 61,
    IRFormatR8Uint                             = 62,
    IRFormatR8Snorm                            = 63,
    IRFormatR8Sint                             = 64,
    IRFormatA8Unorm                            = 65,
    IRFormatR1Unorm                            = 66,
    IRFormatR9G9B9E5Sharedexp                  = 67,
    IRFormatR8G8B8G8Unorm                      = 68,
    IRFormatG8R8G8B8Unorm                      = 69,
    IRFormatBC1Typeless                        = 70,
    IRFormatBC1Unorm                           = 71,
    IRFormatBC1Unorm_sRGB                      = 72,
    IRFormatBC2Typeless                        = 73,
    IRFormatBC2Unorm                           = 74,
    IRFormatBC2Unorm_sRGB                      = 75,
    IRFormatBC3Typeless                        = 76,
    IRFormatBC3Unorm                           = 77,
    IRFormatBC3Unorm_sRGB                      = 78,
    IRFormatBC4Typeless                        = 79,
    IRFormatBC4Unorm                           = 80,
    IRFormatBC4Snorm                           = 81,
    IRFormatBC5Typeless                        = 82,
    IRFormatBC5Unorm                           = 83,
    IRFormatBC5Snorm                           = 84,
    IRFormatB5G6R5Unorm                        = 85,
    IRFormatB5G5R5A1Unorm                      = 86,
    IRFormatB8G8R8A8Unorm                      = 87,
    IRFormatB8G8R8X8Unorm                      = 88,
    IRFormatR10G10B10XRBiasA2Unorm             = 89,
    IRFormatB8G8R8A8Typeless                   = 90,
    IRFormatB8G8R8A8Unorm_sRGB                 = 91,
    IRFormatB8G8R8X8Typeless                   = 92,
    IRFormatB8G8R8X8Unorm_sRGB                 = 93,
    IRFormatBC6HTypeless                       = 94,
    IRFormatBC6HUf16                           = 95,
    IRFormatBC6HSf16                           = 96,
    IRFormatBC7Typeless                        = 97,
    IRFormatBC7Unorm                           = 98,
    IRFormatBC7Unorm_sRGB                      = 99,
    IRFormatAYUV                               = 100,
    IRFormatY410                               = 101,
    IRFormatY416                               = 102,
    IRFormatNV12                               = 103,
    IRFormatP010                               = 104,
    IRFormatP016                               = 105,
    IRFormat420Opaque                          = 106,
    IRFormatYUY2                               = 107,
    IRFormatY210                               = 108,
    IRFormatY216                               = 109,
    IRFormatNV11                               = 110,
    IRFormatAI44                               = 111,
    IRFormatIA44                               = 112,
    IRFormatP8                                 = 113,
    IRFormatA8P8                               = 114,
    IRFormatB4G4R4A4Unorm                      = 115,
    IRFormatP208                               = 130,
    IRFormatV208                               = 131,
    IRFormatV408                               = 132,
    IRFormatSamplerFeedbackMinMipOpaque        = 189,
    IRFormatSamplerFeedbackMipRegionUsedOpaque = 190,
    IRFormatForceUint                          = 0xffffffff,
} IRFormat;

#endif // IRFORMAT_H
