#pragma once
#include "IconsFontAwesome6.h" // icon descriptions, source: https://github.com/juliettef/IconFontCppHeaders

// These map the Font Awesome icon definitions to editor:
//	These definitions will help to change icons that are scattered throughout the editor code
//	Search available icons: https://fontawesome.com/search?q=paper&o=r&m=free
#define ICON_LAYER				ICON_FA_LAYER_GROUP
#define ICON_TRANSFORM			ICON_FA_LOCATION_DOT
#define ICON_MESH				ICON_FA_CUBE
#define ICON_OBJECT				ICON_FA_CUBES
#define ICON_RIGIDBODY			ICON_FA_CUBES_STACKED
#define ICON_SOFTBODY			ICON_FA_FLAG
#define ICON_EMITTER			ICON_FA_FIRE
#define ICON_HAIR				ICON_FA_SEEDLING
#define ICON_FORCE				ICON_FA_WIND
#define ICON_SOUND				ICON_FA_VOLUME_HIGH
#define ICON_VIDEO				ICON_FA_FILM
#define ICON_DECAL				ICON_FA_NOTE_STICKY
#define ICON_CAMERA				ICON_FA_VIDEO
#define ICON_ENVIRONMENTPROBE	ICON_FA_EARTH_ASIA
#define ICON_ANIMATION			ICON_FA_PERSON_RUNNING
#define ICON_ARMATURE			ICON_FA_PERSON
#define ICON_POINTLIGHT			ICON_FA_LIGHTBULB
#define ICON_SPOTLIGHT			ICON_FA_LIGHTBULB // todo: find better one for spotlight
#define	ICON_DIRECTIONALLIGHT	ICON_FA_SUN
#define ICON_MATERIAL			ICON_FA_FILL_DRIP
#define ICON_WEATHER			ICON_FA_CLOUD
#define ICON_BONE				ICON_FA_BONE
#define ICON_IK					ICON_FA_HAND_FIST
#define ICON_NAME				ICON_FA_COMMENT_DOTS
#define ICON_SPRING				ICON_FA_PAPERCLIP
#define ICON_COLLIDER			ICON_FA_CAPSULES
#define ICON_SCRIPT				ICON_FA_SCROLL
#define ICON_HIERARCHY			ICON_FA_ARROWS_DOWN_TO_PEOPLE
#define ICON_EXPRESSION			ICON_FA_MASKS_THEATER
#define ICON_HUMANOID			ICON_FA_PERSON_RAYS
#define ICON_TERRAIN			ICON_FA_MOUNTAIN_SUN
#define ICON_SPRITE				ICON_FA_IMAGE
#define ICON_FONT				ICON_FA_FONT
#define ICON_VOXELGRID			ICON_FA_TABLE_CELLS
#define ICON_CLEARVOXELS		ICON_FA_TRASH_CAN
#define ICON_VOXELIZE			ICON_FA_WAVE_SQUARE
#define ICON_VOXELBOUNDS		ICON_FA_VECTOR_SQUARE
#define ICON_METADATA			ICON_FA_SLIDERS

#define ICON_SAVE				ICON_FA_FLOPPY_DISK
#define ICON_OPEN				ICON_FA_FOLDER_OPEN
#define ICON_CLOSE				ICON_FA_TRASH
#define ICON_FULLSCREEN			ICON_FA_EXPAND
#define ICON_WINDOWED			ICON_FA_COMPRESS
#define ICON_BACKLOG			ICON_FA_BOOK
#define ICON_HELP				ICON_FA_CIRCLE_QUESTION
#define ICON_EXIT				ICON_FA_CIRCLE_XMARK
#define ICON_SCALE				ICON_FA_UP_RIGHT_AND_DOWN_LEFT_FROM_CENTER
#define ICON_ROTATE				ICON_FA_ROTATE_RIGHT
#define ICON_TRANSLATE			ICON_FA_UP_DOWN_LEFT_RIGHT
#define ICON_CHECK				ICON_FA_CHECK
#define ICON_DISABLED			ICON_FA_BAN
#define ICON_BUG				ICON_FA_BUG
#define ICON_PROFILER			ICON_FA_STOPWATCH
#define ICON_CINEMA_MODE		ICON_FA_CLAPPERBOARD
#define ICON_DUMMY				ICON_FA_PERSON_ARROW_UP_FROM_LINE
#define ICON_NAVIGATION			ICON_FA_ROUTE
#define ICON_CONTENT_BROWSER	ICON_FA_ICONS

#define ICON_LEFT_RIGHT			ICON_FA_LEFT_RIGHT
#define ICON_UP_DOWN			ICON_FA_UP_DOWN
#define ICON_UPRIGHT_DOWNLEFT	ICON_FA_UP_RIGHT_AND_DOWN_LEFT_FROM_CENTER
#define ICON_CIRCLE				ICON_FA_CIRCLE
#define ICON_SQUARE				ICON_FA_SQUARE_FULL
#define ICON_CUBE				ICON_FA_CUBE
#define ICON_LOOP				ICON_FA_REPEAT
#define ICON_PINGPONG			ICON_FA_ARROWS_LEFT_RIGHT_TO_LINE
#define ICON_PLAY				ICON_FA_PLAY
#define ICON_BACKWARD           ICON_FA_BACKWARD
#define ICON_FORWARD            ICON_FA_FORWARD
#define ICON_PAUSE				ICON_FA_PAUSE
#define ICON_STOP				ICON_FA_STOP
#define ICON_PEN				ICON_FA_PEN
#define ICON_FILTER				ICON_FA_FILTER
#define ICON_SEARCH				ICON_FA_MAGNIFYING_GLASS
#define ICON_SAVE_EMBED			ICON_FA_FILE_ZIPPER
#define ICON_SAVE_NO_EMBED		ICON_FA_FILE
#define ICON_SAVE_HEADER		ICON_FA_FILE_CODE
#define ICON_LANGUAGE			ICON_FA_LANGUAGE

#define ICON_DARK				ICON_FA_MOON
#define ICON_BRIGHT				ICON_FA_SUN
#define ICON_SOFT				ICON_FA_LEAF
#define ICON_HACKING			ICON_FA_COMPUTER
#define ICON_NORD			    ICON_FA_MOUNTAIN

#define ICON_GENERALOPTIONS		ICON_FA_GEAR
#define ICON_GRAPHICSOPTIONS	ICON_FA_DISPLAY
#define ICON_CAMERAOPTIONS		ICON_CAMERA
#define ICON_MATERIALBROWSER	ICON_MATERIAL
#define ICON_PAINTTOOL			ICON_FA_PAINTBRUSH
