GL_PROC(void, glViewport, (GLint a, GLint b, GLsizei c, GLsizei d))
GL_PROC(void, glLoadIdentity, (void))
GL_PROC(void, glOrtho, (GLdouble a, GLdouble b, GLdouble c, GLdouble d, GLdouble e, GLdouble f))
GL_PROC(void, glVertexPointer, (GLint a, GLenum b, GLsizei c, const GLvoid* d))
GL_PROC(void, glTexCoordPointer, (GLint a, GLenum b, GLsizei c, const GLvoid* d))
GL_PROC(void, glColorPointer, (GLint a, GLenum b, GLsizei c, const GLvoid* d))
GL_PROC(void, glBindTexture, (GLenum a, GLuint b))
GL_PROC(void, glScissor, (GLint a, GLint b, GLsizei c, GLsizei d))
GL_PROC(void, glDrawElements, (GLenum a, GLsizei b, GLenum c, const GLvoid* d))
GL_PROC(void, glClearColor, (GLclampf a, GLclampf b, GLclampf c, GLclampf d))
GL_PROC(void, glEnable, (GLenum a))
GL_PROC(void, glBlendFunc, (GLenum a, GLenum b))
GL_PROC(void, glPolygonMode, (GLenum a, GLenum b))
GL_PROC(void, glEnableClientState, (GLenum a))
GL_PROC(void, glMatrixMode, (GLenum a))
GL_PROC(void, glGenTextures, (GLsizei a, GLuint *b))
GL_PROC(void, glTexParameteri, (GLenum a, GLenum b, GLint c))
GL_PROC(void, glPixelStorei, (GLenum a, GLint b))
GL_PROC(void, glTexImage2D, (GLenum a, GLint b, GLint c, GLsizei d, GLsizei e, GLint f, GLenum g, GLenum h, const GLvoid *i))
GL_PROC(void, glDisable, (GLenum a))
GL_PROC(void, glClear, (GLbitfield a))
GL_PROC(void, glDeleteTextures, (GLsizei a, const GLuint *b))
